server:
  port: 8080

spring:
  application:
    name: department-service'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: beyond
    password: beyond
  data:
    redis:
      host: localhost
      username: default
      password: beyond
      port: 6379


mybatis:
  type-aliases-package: com.beyond.university.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL

jwt:
  ㅐ: http://acoounts.beyond.com
  secret: h1o2n3g4g5i6l7d8o9n0g;h1o2n3g4g5i6l7d8o9n0gh
